defaults:
  - default
  - preprocessing: preprocess
  - evaluation: eval_classification

preprocessing:
  method:
    map:
      function:
        template: "{}"
    set_transform:
      transform:
        image_root: ${run.m3exam_image_root}
        extension: ""
