defaults:
  - default
  - preprocessing: preprocess
  - evaluation: eval_grounding

preprocessing:
  method:
    map:
      function:
        template: "Please provide the bounding box coordinate of the region this sentence describes: {}"
    set_transform:
      transform:
        image_root: ${run.flickr_image_root}
        extension: ""
