defaults:
  - /dataspec@task_mix: task_mix
  - override /dataspec/dataloader@task_mix.dataloader: train

task_mix:
  dataset:
    split: train
    path: json
    data_files: ${run.train_data}/${run.train_file}
