model_checkpoint_on_epoch:
  _target_: lightning.pytorch.callbacks.ModelCheckpoint
  monitor: null # name of the logged metric which determines when model is improving
  every_n_epochs: 1
  verbose: false
  save_top_k: -1 # -1 -> all models are saved
#  filename: "epoch={epoch}"
  save_last: false # additionaly always save model from last epoch
  dirpath: "${hydra:runtime.output_dir}/checkpoints/"
  save_weights_only: true
  auto_insert_metric_name: false
